### ISSUE TITLE
Supporting more than 5 links?

### ISSUE THREAD

**Issue by red8888** [tdelenikas/comm2ip#1]
You say it supports up to 5 links (code configurable). 

By "code configurable" do you mean I can just add more bindings in the config file and it will just work or I have to modify the source code and recompile? 

If this requires editing the source could you give me a little clue as to where I should make this change?

Thanks a lot! Hope the issue tracker is an ok place to ask this question.

**Comment by tdelenikas** [comment]
Hi,

Check the code: https://github.com/smslib/comm2ip/blob/master/Comm2IPService/Comm2IPService/Comm2IPService.cs

Modify `MAX_THREADS` and the related code, like the section where it reads configuration data from `Properties.Settings.Default.BindingNN`

Hope this helps.

**Comment by tdelenikas** [comment]
I should also make clear that the current codebase supports up to 5 links without touching the code. If you want more connections, you should definitely alter the code a bit and recompile.

**Comment by red8888** [comment]
Hey thanks for getting back to me. I'm not very experienced with C#, but it doesn't look terribly complicated.
