### ISSUE TITLE
Prevent comm2ip from echoing back the commands I send it to the terminal.

### ISSUE THREAD

**Issue by red8888** [tdelenikas/comm2ip#2]
I'm running the comm2ip service on a windows 7 box. 

I have a comm port connected to a Cisco router's console port.

I connect to the win 7 box running the service via putty and I'm redirected to the comm port connect to the router.

So far the program has been working great except for one thing. It echos back all of the commands I type to the terminal. For example if I type "show interfaces" it will echo "show interfaces" back to the terminal before running the actual command.

Is there a way to disable this behavior?

**Comment by tdelenikas** [comment]
I don't think that this is a comm2ip issue.
I think that you should disable echo from the target device. Do you have / have you tried such an option?
