### ISSUE TITLE
Serial port not accessible for fast reconnect.

### ISSUE THREAD

**Issue by tobiascapin** [tdelenikas/comm2ip#3]
I found a little trouble in case of serial reconnect. If the serialport is closed and opened just after I got a "System.UnauthorizedAccessException" for unavailable port. 
To reprocude it, try to do a fast socket reconnection.

Note from SerialPort.Close method msdn docs:

> The best practice for any application is to wait for some amount of time after calling the Close method before attempting to call the Open method, as the port may not be closed instantly.

To avoid this I suggest to create a single SerialPort per port and use always the same object for each tcp socket thread. Moreover, I think the Send() method to SerialPort should be synchronized between threads.

Anyway, thanks for this nice library!

**Comment by tdelenikas** [comment]
Hi!

You are right, there probably should be a delay after port closing ("some amount of time" is not very clear though...)

The _static_ SerialPort per port is a nice idea.

About the synchronization, I am a bit confused: Why do you suggest a synced write? I mean, do you ever expect multiple ip connections to write to the _same_ port? Let me know what scenario you have in mind.

Thanks!

**Comment by tobiascapin** [comment]
I think that you should use a static dictionary of serialports and reuse the same object every time without closing it for every tcpclient disconnection otherwise you will not be able to reopen it for "a while". 

About the synchronization I mean that you are admitting many tcp clients to the same port, that these should write to the same serial port together, otherwise you should lock tcp connections when there is another active connection to that port.

Thanks!

**Comment by tdelenikas** [comment]
Yes, I agree with the dictionary solution.

What I don't understand however why would you want multiple IP sources to send traffic to a single com port.  This library does not support this session-like conversation. I could certainly (and I will) sync the writes, but this will be the least of your problems. Unless you really don't care about the com port responses in your scenario.

Thank you :)

**Comment by tobiascapin** [comment]
An example:  I have a serial thermal printer connect to a PC. I want to print here from many hosts connected in the same network. Why this scenario I can print ticket or labels from many PC in the network. 
If you do not think that your library fits this requirements I suggest to limit one client socket per serial port.
Thanks!

**Comment by tdelenikas** [comment]
Hello,

Can you test-run the latest "dev" branch? It has some optimizations regarding the "fast reconnect" issue you've reported. It implements the dictionary proposal. However, the only-one-socket-per-port issue remains - the solution here is not trivial...

**Comment by tobiascapin** [comment]
Yes! Now it is working also with fast reconnection. Another little problem is that I can not choose 0.0.0.0 as tcp listening ip address. This ip should be accepted by CheckParameters() method because it is equals to IPAddress.Any.

**Comment by tdelenikas** [comment]
This is not complete, I know I need to add some locks just to be on the safe side. But I am glad this works for you.

I will also check your observation about the special "0.0.0.0" inet.

Thanks!

**Comment by tdelenikas** [comment]
All merged to master, tagged v1.0.2.
