### ISSUE TITLE
Bombs

### ISSUE THREAD

**Issue by scargill** [tdelenikas/comm2ip#4]
At least on Windows 10 64 bit, this bombs if you use any other than 127.0.0.1 as an address.  The service mode doesn't show any sign of bombing - but doesn't work.

**Comment by tdelenikas** [comment]
Hello,

Can you please explain this a bit more?

**Comment by scargill** [comment]
When you run the command line and try to use any address than as in the example - ie 127.0.0.1 - a host of exceptions come up and it fails.

**Comment by tdelenikas** [comment]
The app binds locally. The IP you use should be available on the machine you run this utility.

**Comment by scargill** [comment]
Ah, right – no good – I wanted it to put a COM port on the local machine, from a microcontroller talking by WIFI on a specific address at port 23.

Not sure WHY the IP address has to be on the same machine??!!?? 

Ok, thanks.
